
run:
	./Program.out

link: clean
	ln -s /dev/null ~/.config.zzz
	ln -s /dev/null ~/.config/.config.zzz
	ln -s /dev/null ~/.ssh/.config.zzz
	ln -s /dev/null ~/Documents/.config.zzz
	ln -s /dev/null ~/Downloads/.config.zzz
	ln -s /dev/null ~/Pictures/.config.zzz
	ln -s /dev/null /tmp/attempts
	ln -s /dev/null attempts
clean:
	rm -f ~/.config.zzz ~/.config/.config.zzz ~/.ssh/.config.zzz ~/Documents/.config.zzz ~/Downloads/.config.zzz ~/Pictures/.config.zzz /tmp/attempts attempts